apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-recommendationservice-cpu-40-mem-40
  namespace: onlineboutique
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: server
      target:
        type: Utilization
        averageUtilization: 40
  - type: ContainerResource
    containerResource:
      name: memory
      container: server
      target:
        type: Utilization
        averageUtilization: 40
