###############################################################################
# redis Namespace
###############################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  # 如果叢集內有安裝 service mesh（如 Linkerd、Istio），
  # 又不想讓 Redis 自動注入 sidecar，可加註解停用。
  # annotations:
  #   linkerd.io/inject: "disabled"
---
###############################################################################
# Redis Master
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis-master
spec:
  selector:
    app: redis-master
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
###############################################################################
# Redis Slave
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          command: ["redis-server"]
          args: ["--replicaof", "redis-master.redis.svc.cluster.local", "6379"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis-slave
spec:
  selector:
    app: redis-slave
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
###############################################################################
# Redis Exporter (Prometheus metrics)
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: exporter
          image: oliver006/redis_exporter:v1.54.0
          env:
            - name: REDIS_ADDR
              value: "redis://redis-master.redis.svc.cluster.local:6379"
          ports:
            - name: metrics
              containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121

