apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-redis-master-cpu-60-mem-40
  namespace: redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-master
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: redis
      target:
        type: Utilization
        averageUtilization: 60
  - type: ContainerResource
    containerResource:
      name: memory
      container: redis
      target:
        type: Utilization
        averageUtilization: 40
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-redis-slave-cpu-60-mem-40
  namespace: redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-slave
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: redis
      target:
        type: Utilization
        averageUtilization: 60
  - type: ContainerResource
    containerResource:
      name: memory
      container: redis
      target:
        type: Utilization
        averageUtilization: 40