apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingressgateway
  namespace: prometheus      # ← 跟 Prometheus 安裝同一 ns
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway   # service 的 label
  namespaceSelector:
    matchNames: [istio-system]
  endpoints:
    # 1️⃣ 先用 gateway Service 已經有的 15021 來做 service discover
    - port: status-port           # <- svc 原本就有
      path: /stats/prometheus     # Envoy metrics 路徑
      interval: 15s
      scheme: http
      # 2️⃣ 把 __address__ 換成 PodIP:15090
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_ip]
          action: replace
          targetLabel: __address__
          regex: (.*)
          replacement: $1:15090

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: prometheus
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy
  namespace: prometheus          # 建議放在跟 Prometheus 同一個 ns
  labels:
    release: prometheus-stack    # 必須和 kube-prometheus-stack 的 release label 相同
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio   # 任何被 sidecar 注入的 Pod 都有這個標籤
  namespaceSelector:
    any: true                            # 抓整個叢集的 sidecar
  podMetricsEndpoints:
    - port: http-envoy-prom              # ← 改成 **名稱**
      path: /stats/prometheus            # Istio / Envoy metrics
      interval: 15s

---
# jaeger-sampling.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-sampling
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0

