apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-redis-cart-cpu-60-mem-40
  namespace: onlineboutique
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-cart
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: redis
      target:
        type: Utilization
        averageUtilization: 60
  - type: ContainerResource
    containerResource:
      name: memory
      container: redis
      target:
        type: Utilization
        averageUtilization: 40
